### ISSUE TITLE
Syntax highlighter breaks down on XML namespaces: mismatched input '=' expecting LPAREN

### ISSUE THREAD

**Issue by fatso83** [antlr/jetbrains-plugin-st4#40]
As the below screenshot shows, I get a bunch of errors on string template group files with XML. Most of these seem related to using XML namespaces, where the error shows `mismatched input '=' expecting LPAREN` on encountering something like `s:mustUnderstand`.
![2022-10-13_09-13](https://user-images.githubusercontent.com/618076/195527982-863713b4-8dca-45d3-aaf4-cdf13df1f017.png)

This example, using `§` for variables (`§messageId§`) is sufficient to display the error:
#### saml.stg
```xml
SamlAssertionRequest(messageId, to, createdAt, expiresAt, accessToken, target) ::= <<
<s:Envelope xmlns:s="http://www.w3.org/2003/05/soap-envelope" xmlns:a="http://www.w3.org/2005/08/addressing" xmlns:u="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd">
       <s:Header>
             <a:Action s:mustUnderstand="1">http://docs.oasis-open.org/ws-sx/ws-trust/200512/RST/Issue</a:Action>
             <a:MessageID>urn:uuid:§messageId§</a:MessageID>
             <a:ReplyTo>
                    <a:Address>http://www.w3.org/2005/08/addressing/anonymous</a:Address>
             </a:ReplyTo>
       </s:Header>
</s:Envelope>
>>
```

Also seen that syntax highlighting breaks down on simple HTML too:
![2022-10-13_09-15](https://user-images.githubusercontent.com/618076/195527976-e8c5c755-45b0-44b9-b1a9-86d207ecda56.png)

To be honest, I am not totally sure what this plugin is supposed to apart from some syntax highlighting, but it works pretty well (i.e. no errors) on JSON.

Marked the files manually using the correct filetype:
![2022-10-13_09-28](https://user-images.githubusercontent.com/618076/195530579-73f09681-9ad8-467a-a357-8ff8962123e1.png)

**Comment by parrt** [comment]
Hi. Sorry for the issues. I haven't touched this in quite a while but yes it was mainly for syntax highlighting enlisting the rules in the structure pane.

**Comment by bjansen** [comment]
@fatso83 the plugin is trying to highlight variables in your template. By default, variables are surrounded with `<>`, but your XML/HTML templates are also containing `<>` which the plugin tries to parse as valid StringTemplate.
Adding a `delimiters` declaration on top of your file is enough to fix this confusion and make the plugin look for `§§` instead of `<>`:

<img width="1013" alt="image" src="https://github.com/antlr/jetbrains-plugin-st4/assets/281528/bf304232-5438-4b48-b158-0f57f7a066cc">

Syntax highlighting also works:

<img width="1006" alt="image" src="https://github.com/antlr/jetbrains-plugin-st4/assets/281528/753d15be-581b-4c51-8e0b-c85e9a3eb6ff">

I'll update the readme to clarify how to fix this kind of problems.
